; File generated by CompCert 3.14
; Command line: -S foo.c
	.text
	.balign 4
	.globl _foo
_foo:
	mov	x15, sp
	sub	sp, sp, #16
	str	x15, [sp, #0]
	str	x30, [sp, #8]
	bl	_foo1
	bl	_foo2
	orr	w0, wzr, #2
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
