# File generated by CompCert 3.8
# Command line: -stdlib ../../runtime -dc -dclight -dasm -o fib.compcert_gcc fib.c -lm
	.option nopic
	.option norelax
	.option norvc
	.section	.rodata
	.balign 1
__stringlit_1:
	.ascii	"fib(%d) = %d\012\000"
	.type	__stringlit_1, @object
	.size	__stringlit_1, . - __stringlit_1
	.text
	.balign 2
	.globl fib
fib:
	mv	x30, x2
	addi	x2, x2, -16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	sw	x8, 8(x2)
	sw	x9, 12(x2)
	mv	x9, x10
	addi	x31, x0, 2
	blt	x9, x31, .L100
	addi	x10, x9, -1
	call	fib
	mv	x8, x10
	addi	x10, x9, -2
	call	fib
	add	x10, x8, x10
	j	.L101
.L100:
	addi	x10, x0, 1
.L101:
	lw	x8, 8(x2)
	lw	x9, 12(x2)
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.type	fib, @function
	.size	fib, . - fib
	.text
	.balign 2
	.globl main
main:
	mv	x30, x2
	addi	x2, x2, -16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	sw	x8, 8(x2)
	addi	x31, x0, 2
	blt	x10, x31, .L102
	lw	x10, 4(x11)
	call	atoi
	mv	x8, x10
	j	.L103
.L102:
	addi	x8, x0, 35
.L103:
	mv	x10, x8
	call	fib
	mv	x12, x10
	lui	x10, %hi(__stringlit_1)
	addi	x10, x10, %lo(__stringlit_1)
	mv	x11, x8
	call	printf
	addi	x10, x0, 0
	lw	x8, 8(x2)
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.type	main, @function
	.size	main, . - main
